from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Date, Text, Float
from base import Base

class App(Base):
    __tablename__ = 'apps'
    id = Column(String, primary_key=True)
    android_version = Column(String)
    description = Column(String)
    developer = Column(String)
    developer_id = Column(String)
    genre = Column(String)
    genre_id = Column(String)
    count_1_star = Column(Integer)
    count_2_star = Column(Integer)
    count_3_star = Column(Integer)
    count_4_star = Column(Integer)
    count_5_star = Column(Integer)
    min_installs = Column(Integer)
    ratings = Column(Integer)
    released = Column(String)
    reviews = Column(Integer)
    score = Column(Float)
    size = Column(String)
    title = Column(String)
    updated = Column(Date)
    url = Column(String)
    version = Column(String)

    def __init__(self, **kwargs):
        self.id = kwargs.get('id')
        self.android_version = kwargs.get('android_version')
        self.description = kwargs.get('description')
        self.developer = kwargs.get('developer')
        self.developer_id = kwargs.get('developer_id')
        self.genre = kwargs.get('genre')
        self.genre_id = kwargs.get('genre_id')
        self.count_1_star = kwargs.get('count_1_star')
        self.count_2_star = kwargs.get('count_2_star')
        self.count_3_star = kwargs.get('count_3_star')
        self.count_4_star = kwargs.get('count_4_star')
        self.count_5_star = kwargs.get('count_5_star')
        self.min_installs = kwargs.get('min_installs')
        self.ratings = kwargs.get('ratings')
        self.released = kwargs.get('released')
        self.reviews = kwargs.get('reviews')
        self.score = kwargs.get('score')
        self.size = kwargs.get('size')
        self.summary = kwargs.get('summary')
        self.title = kwargs.get('title')
        self.updated = kwargs.get('updated')
        self.url = kwargs.get('url')
        self.version = kwargs.get('version')
